<?php

/**
 *
 * @file
 * API for handling file uploads and server file management.
 */

/**
 * Page callback for ads page.
 *
 * @return string
 */
function my_menu_ads_page() {
  return t("Страница с объявлениями");
}

/**
 * Page callback for buy ads page.
 *
 * @return string
 */
function my_menu_buy_ads_page() {
  return t("Страница с объявлениями о покупке");
}

/**
 * Page callback for sell ads page.
 *
 * @return string
 */
function my_menu_sell_ads_page() {
  return t("Страница с объявлениями о продаже");
}

/**
 * Page callback for add ads page.
 *
 * @return string
 */
function my_menu_add_ads_page() {
  return t("Добавить объявление");
}

/**
 * Page callback for catalogue page.
 *
 * @return string
 */
function my_menu_catalogue_page() {
  return t("Каталог услуг");
}

/**
 * Page callback for catalogue dealership page.
 *
 * @return string
 */
function my_menu_catalogue_dealership_page() {
  return t("Каталог автосалонов");
}

/**
 * Page callback for catalogue shop page.
 *
 * @return string
 */
function my_menu_catalogue_shop_page() {
  return t("Каталог автомагазинов");
}

/**
 * Page callback for review page.
 *
 * @return string
 */
function my_menu_review_page() {
  return t("Добавить отзыв");
}
