<?php
/**
 * @file
 * My own menu on toolbar.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 *
 * @param arg
 *   Array that holds the current path as returned from arg() function
 *
 * @return string
 *   String
 */
function my_menu_help($path, $arg) {
  switch ($path) {
    case "admin/help#my_menu":
      return '' . t("This is my menu.") . '';
      break;

  }
}

/**
 * Implements hook_block_info().
 *
 * @return
 *  name and settings of the block
 */
function my_menu_block_info() {
  $blocks['my_menu'] = [
    // The name that will appear in the block list.
    'info' => t('My menu'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  ];
  return $blocks;
}

/**
 * Implements hook_menu().
 *
 * A simple example which defines a page callback and a menu entry.
 *
 * @return
 *    items
 */

function my_menu_menu() {
  $items['admin/ads'] = [
    'title' => 'Объявления',
    'description' => 'Страница с объявлениями',
    'page callback' => 'my_menu_ads_page',
    'file' => 'my_menu.pages.inc',
    'menu_name' => 'menu-test',
    'expanded' => TRUE,
    'access callback' => TRUE,
  ];
  $items['admin/ads/buy'] = [
    'title' => 'Куплю',
    'description' => 'Страница с объявлениями о покупке',
    'page callback' => 'my_menu_buy_ads_page',
    'access callback' => TRUE,
    'file' => 'my_menu.pages.inc',
    'menu_name' => 'menu-test',
    'expanded' => TRUE,
  ];
  $items['admin/ads/sell'] = [
    'title' => 'Продам',
    'description' => 'Страница с объявлениями о продаже',
    'page callback' => 'my_menu_sell_ads_page',
    'access callback' => TRUE,
    'file' => 'my_menu.pages.inc',
    'menu_name' => 'menu-test',
    'expanded' => TRUE,
  ];
  $items['admin/ads/add'] = [
    'title' => 'Добавить объявление',
    'description' => 'Добавление объявления',
    'page callback' => 'my_menu_add_ads_page',
    'file' => 'my_menu.pages.inc',
    'menu_name' => 'menu-test',
    'access arguments' => array('access to ads'),
    'expanded' => TRUE,
  ];
  $items['admin/catalogue'] = [
    'title' => 'Каталог',
    'description' => 'Каталог услуг',
    'page callback' => 'my_menu_catalogue_page',
    'access callback' => TRUE,
    'file' => 'my_menu.pages.inc',
    'menu_name' => 'menu-test',
    'expanded' => TRUE,
  ];
  $items['admin/catalogue/dealership'] = [
    'title' => 'Автосалоны',
    'description' => 'Каталог автосалонов',
    'page callback' => 'my_menu_catalogue_dealership_page',
    'access callback' => TRUE,
    'file' => 'my_menu.pages.inc',
    'menu_name' => 'menu-test',
    'expanded' => TRUE,
  ];
  $items['admin/catalogue/shop'] = [
    'title' => 'Магазины',
    'description' => 'Каталог магазинов',
    'page callback' => 'my_menu_catalogue_shop_page',
    'access callback' => TRUE,
    'file' => 'my_menu.pages.inc',
    'menu_name' => 'menu-test',
    'expanded' => TRUE,
  ];
  $items['admin/review'] = [
    'title' => 'Добавить отзыв',
    'description' => 'Добавить отзыв о сервисе',
    'page callback' => 'my_menu_review_page',
    'file' => 'my_menu.pages.inc',
    'menu_name' => 'menu-test',
    'access arguments' => array('access to reviews'),
    'expanded' => TRUE,
  ];
  return $items;
}

/**
 * Implements hook_permission().
 *
 * Provides a demonstration access string.
 */
function my_menu_permission() {
  return array(
    'access to ads' => array(
      'title' => t('Access to adding ads'),
      'description' => t('Perform administration tasks for my module.'),
    ),
    'access to reviews' => array(
      'title' => t('Access to adding reviews'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}
