<?php

/**
 *
 * @file
 * API for handling file uploads and server file management.
 */

function ads_page() {
  return t("Страница с объявлениями");
}

function buy_ads_page() {
  return t("Страница с объявлениями о покупке");
}

function sell_ads_page() {
  return t("Страница с объявлениями о продаже");
}

function add_ads_page() {
  return t("Добавить объявление");
}

function catalogue_page() {
  return t("Каталог услуг");
}

function catalogue_dealership_page() {
  return t("Каталог автосалонов");
}


function catalogue_shop_page() {
  return t("Каталог автомагазинов");
}

function review_page() {
  return t("Добавить отзыв");
}
